// AUTO-GENERATED by sv-unity-runner. Do not hand-edit.
// Regenerated whenever the runner detects a stale / missing copy.
// You may commit or gitignore this folder; the runner is idempotent either way.

#if UNITY_INCLUDE_TESTS
using System;
using System.Globalization;
using System.IO;
using System.Text;
using NUnit.Framework.Interfaces;
using SvUnityRunner.Injected;
using UnityEngine;
using UnityEngine.TestRunner;

[assembly: TestRunCallback(typeof(SvUnityRunnerTestRunCallback))]

namespace SvUnityRunner.Injected
{
    /// <summary>
    /// Writes NUnit results to Application.persistentDataPath/sv_unity_runner_results.xml
    /// when the test run finishes, via temp-file-then-atomic-rename so a polling
    /// reader never observes partial XML. The runner polls for this file
    /// appearing and proactively kills the editor + player once results are on
    /// disk, instead of waiting on Unity's internal callback timeout.
    ///
    /// Active in both --build-mode development (where it's redundant with
    /// PlayerConnection but harmless) and release (where it's the ONLY way
    /// results make it back, since PlayerConnection.Send is engine-no-op'd
    /// in non-Development builds).
    /// </summary>
    public class SvUnityRunnerTestRunCallback : ITestRunCallback
    {
        private const string ResultsFileName = "sv_unity_runner_results.xml";

        public void RunStarted(ITest testsToRun) { }

        public void TestStarted(ITest test) { }

        public void TestFinished(ITestResult result) { }

        public void RunFinished(ITestResult testResults)
        {
            var dir = Application.persistentDataPath;
            var finalPath = Path.Combine(dir, ResultsFileName);
            var tmpPath = finalPath + ".tmp";
            try
            {
                // ITestResult.ToXml gives us the <test-suite> tree only. The
                // runner's parser (and Unity's own editor-side writer) expect
                // a <test-run> wrapper carrying the run-level summary
                // attributes (total/passed/failed/result/duration/etc.).
                // Hand-roll the wrapper so the on-disk file matches the
                // standard NUnit/Unity testresults.xml shape.
                var inner = testResults.ToXml(true).OuterXml;
                var total =
                    testResults.PassCount
                    + testResults.FailCount
                    + testResults.SkipCount
                    + testResults.InconclusiveCount;
                var sb = new StringBuilder();
                sb.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
                sb.Append("<test-run id=\"2\"");
                sb.AppendFormat(" testcasecount=\"{0}\"", total);
                sb.AppendFormat(" result=\"{0}\"", testResults.ResultState);
                sb.AppendFormat(" total=\"{0}\"", total);
                sb.AppendFormat(" passed=\"{0}\"", testResults.PassCount);
                sb.AppendFormat(" failed=\"{0}\"", testResults.FailCount);
                sb.AppendFormat(" inconclusive=\"{0}\"", testResults.InconclusiveCount);
                sb.AppendFormat(" skipped=\"{0}\"", testResults.SkipCount);
                sb.AppendFormat(" asserts=\"{0}\"", testResults.AssertCount);
                sb.AppendFormat(
                    " duration=\"{0}\"",
                    testResults.Duration.ToString(CultureInfo.InvariantCulture)
                );
                sb.Append(">\n");
                sb.Append(inner);
                sb.Append("\n</test-run>\n");

                File.WriteAllText(tmpPath, sb.ToString());
                if (File.Exists(finalPath))
                {
                    File.Delete(finalPath);
                }
                // Atomic rename: a runner-side Path.exists() on finalPath
                // implies the content is fully written.
                File.Move(tmpPath, finalPath);
            }
            catch (Exception ex)
            {
                Debug.LogError(
                    "SvUnityRunner: failed to write results XML to " + finalPath + ": " + ex
                );
            }
        }
    }
}
#endif
