// AUTO-GENERATED by sv-unity-runner. Do not hand-edit.
// Regenerated whenever the runner detects a stale / missing copy.
// You may commit or gitignore this folder; the runner is idempotent either way.

using System;
using SvUnityRunner.Injected;
using UnityEditor;
using UnityEditor.TestTools;

[assembly: TestPlayerBuildModifier(typeof(SvUnityRunnerBuildModifier))]

namespace SvUnityRunner.Injected
{
    /// <summary>
    /// Toggled by the SV_UNITY_RUNNER_BUILD_MODE env var the runner sets
    /// before launching Unity. `release` strips Development+AllowDebugging
    /// for benchmark / shipping-flavor measurement; anything else (including
    /// unset) leaves Unity's defaults intact.
    /// </summary>
    public class SvUnityRunnerBuildModifier : ITestPlayerBuildModifier
    {
        public BuildPlayerOptions ModifyOptions(BuildPlayerOptions options)
        {
            var mode = Environment.GetEnvironmentVariable("SV_UNITY_RUNNER_BUILD_MODE");
            if (mode != "release")
            {
                return options;
            }

            // Keep ConnectToHost — stripping it has no upside (PlayerConnection
            // is already engine-no-op'd by the missing Development flag) and
            // changing more options than necessary is hostile to debugging.
            options.options &= ~(BuildOptions.Development | BuildOptions.AllowDebugging);
            return options;
        }
    }
}
